server:
  port: 34629

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: myResume
  couchbase:
    bootstrap-hosts: localhost
    bucket:
      name: myresume
      password: A5Xbd9DgB7BFnrY
  data:
    couchbase:
      auto-index: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

management:
  endpoint:
    health:
      couchbase:
        enabled: true
      show-detail: always
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org:
      apache: ERROR
      springframework: ERROR
    com:
      onimurasame:
        myresume: INFO
      couchbase:
        client: ERROR
    springfox: ERROR


info:
  app:
    name: \${spring.application.name}
    version: ${version}
    buildDate: ${buildDate}
